/home/noxon/coding/C/esiee-in301/libcomm/logger.h File Reference
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
Enumerations
enum LOG_TYPES { call_type,
msg_type,
unkown_type
 }
Functions
int init_log (const char *filename)
void log_call (const char *msg, char *func_name, const char *args,...)
void log_smth (const char *msg)
void private_log_call (const char *msg, const char *func_name, va_list args)
void private_write_log (int log_type, const char *msg)
Detailed Description
Author: Christopher Rabotin. Logger permet de logguer l'activité du programme.
 Les méthodes présentes ici permettrons d'éviter d'utiliser printf() afin de savoir précisément d'où l'appel a été effectué et l'heure de cet appel. -- La fonction de trace est basée sur un code C++: http://www.codeproject.com/KB/cpp/cmtrace.aspx .
Definition in file logger.h.
Enumeration Type Documentation
enum LOG_TYPES
Enumerator:
call_type
msg_type
unkown_type
Definition at line 56 of file logger.h.
Function Documentation
int init_log (const char * filename)
Permet d'initialiser le fichier de log en vérifiant si le fichier peut-être ouvert en écriture.
 Si DEBUG_TO_STDOUT est défini, alors l'appel à cette fonction n'est pas nécessaire avant de logguer. Au contraire, un message sera affiché dans stderr si la fonction de log est appelée avec l'init.
Parameters:
*filename nom du fichier
Returns: Bernouilli: 0 <=> échec | 1 <=> succès
Definition at line 5 of file logger.c.
References filename.
void log_call (const char * msg, char * func_name, const char * args, ...)
Permet de tracer une fonction, avec les paramètres passés, puis appelle private_log_call(). Si DEBUG_TO_STDOUT est défini, alors le message de log est affiché dans stdout. Tous les logs concernant les fonctions seront précédés d'un [*].
Parameters:
*msg le message à être loggué
*func_name nom de la fonction
*args arguments passés à la fonction
... signifie qu'il peut y avoir plusieurs arguments. Pour les extraire, on utilisera stdarg.h
Exemples d'utilisation:
Cas général: log_call(`si erreur, vérifier paramètres`, fct, format, fct_arg1, fct_arg2, fct_arg3);
Exemples de TestLogger.c:
log_call(`dans testParamInt`, `testParamInt`, `(%d,%d)`, arg1, arg2);
log_call(`dans testParamChar`, `testParamChar`, `(\`s\`)`, str);
log_smth(`Okeille c'est bon, l'init est passé youpi!`);
Definition at line 15 of file logger.c.
References private_log_call().
void log_smth (const char * msg)
Permet de logguer un message divers.
Parameters:
msg le message à être loggué
Definition at line 25 of file logger.c.
References private_write_log(), and unkown_type.
void private_log_call (const char * msg, const char * func_name, va_list args)
Permet de logguer l'appel à une fonction, avec des paramètres. Il n'est pas conseillé d'appeler cetter fonction directement! Passez plutôt par `log` qui s'occupe de tout.
Parameters:
*msg le message à être loggué
*func_name nom de la fonction
*args arguments passés à la fonction
Definition at line 32 of file logger.c.
References call_type, and private_write_log().
Referenced by log_call().
void private_write_log (int log_type, const char * msg)
Permet d'écrire le log d'un message passé, suivant le type de log
Parameters:
log_type type de log, voir l'enum plus haut
msg le message à être loggué
Definition at line 39 of file logger.c.
References call_type, filename, and msg_type.
Referenced by log_smth(), and private_log_call().