/home/noxon/coding/C/esiee-in301/terminal.c File Reference
#include `terminal.h`
Functions
int main (void)
void terminal (FILE *commercants, FILE *actions)
void envoie_ordre (FILE *out)
Function Documentation
void envoie_ordre (FILE * out)
Definition at line 100 of file terminal.c.
Referenced by main(), and terminal().
int main (void)
Terminal prend deux descripteurs de fichiers en paramètre vers lesquels il redirige son entrée et sa sortie standards.
Definition at line 8 of file terminal.c.
References envoie_ordre(), and terminal().
void terminal (FILE * commercants, FILE * actions)
Definition at line 26 of file terminal.c.
References alea(), aleainit(), create_msg(), envoie_ordre(), log_msg(), and msg_to_str().
Referenced by main().