/home/noxon/coding/C/esiee-in301/src-test/TestLogger.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include `../libcomm/logger.c`
Functions
void testParamChar (const char *str)
int testParamInt (int arg1, int arg2)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 20 of file TestLogger.c.
References init_log(), log_smth(), and testParamInt().
void testParamChar (const char * str)
author Christopher Rabotin
Definition at line 9 of file TestLogger.c.
References log_call().
Referenced by testParamInt().
int testParamInt (int arg1, int arg2)
Definition at line 14 of file TestLogger.c.
References log_call(), and testParamChar().
Referenced by main().