/home/noxon/coding/C/esiee-in301/src-test/TestMessage.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <malloc.h>
#include `../libcomm/message.h`
#include `../libbourse/alea.h`
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Programme de test des fonctions messages
Definition at line 10 of file TestMessage.c.
References alea(), aleainit(), decoupe(), and message().