/home/noxon/coding/C/esiee-in301/libcomm/message.h File Reference
#include `../casual_includes.h`
#include `./logger.h`
Data Structures
struct msg_struct
Typedefs
typedef struct msg_struct msg
Functions
msg * create_msg (const char *emetteur, const char *type, const char *action, const char *valeur)
char * msg_to_str (msg *msg)
msg * str_to_msg (char *str)
int decoupe (char *message, char *emeteur, char *type, char *action, char *valeur)
char * message (char *emeteur, char *type, char *action, char *valeur)
void log_msg (const char *un_msg, msg *damsg)
Typedef Documentation
typedef struct msg_struct msg
Function Documentation
msg* create_msg (const char * emetteur, const char * type, const char * action, const char * valeur)
create_msg: Construction du message. Le message est alloué dans la fonction.
Parameters:
*emeteur émeteur du message
*type type du message
*action identificateur de l'action
*valeur valeur associée au message
Returns: le message de type msg
Definition at line 28 of file message.c.
References msg_struct::action, msg_struct::emetteur, log_call(), msg_struct::type, and msg_struct::valeur.
Referenced by str_to_msg(), and terminal().
int decoupe (char * message, char * emeteur, char * type, char * action, char * valeur)
decoupe: Decoupe du message
Parameters:
*message le texte du message
*emeteur émeteur du message
*type type du message
*action identificateur de l'action
*valeur valeur associée au message
Returns: 0 si erreur, 1 sinon ATTENTION: Les paramètres étant des pointeurs, les variables associées DOIVENT être allouées avant l'appel de la fonction
Definition at line 3 of file message.c.
void log_msg (const char * un_msg, msg * damsg)
Permet de logguer les ordres de transaction. Placé dans message.h puisque utilisé uniquement pour les messages.
Parameters:
un_msg message d'explication lié à l'ordre de transaction
damsg l'ordre à être loggué.
Definition at line 74 of file message.c.
References msg_struct::action, msg_struct::emetteur, msg_type, private_write_log(), msg_struct::type, and msg_struct::valeur.
Referenced by msg_to_str(), and terminal().
char* message (char * emeteur, char * type, char * action, char * valeur)
message: Construction du message. Le message est alloué dans la fonction.
Parameters:
*emeteur émeteur du message
*type type du message
*action identificateur de l'action
*valeur valeur associée au message
Returns: le message construit suivant le protocole à partir des arguments
Definition at line 15 of file message.c.
Referenced by msg_to_str().
char* msg_to_str (msg * msg)
msg_to_str: transforme le message msg en une chaine de caractères suivant le protocole utilisé Fait appel à message()
Definition at line 50 of file message.c.
References msg_struct::action, msg_struct::emetteur, log_msg(), message(), msg_struct::type, and msg_struct::valeur.
Referenced by terminal().
msg* str_to_msg (char * str)
str_to_msg: transforme une chaine de caractères en msg suivant le protocole utilisé Fait appel à create_msg()
Definition at line 57 of file message.c.
References create_msg().